# Generated by Django 4.1.6 on 2023-05-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BOARD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MEDIUM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medium', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='STANDARD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Standard', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=30)),
                ('Student_Board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studata.board')),
                ('Student_Medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studata.medium')),
                ('Student_Standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studata.standard')),
            ],
        ),
    ]
